app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('inflows.urls')),
    path('', include('suppliers.urls'))

]

inflows/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('inflows/list/', views.InflowListView.as_view(), name='inflow_list'),
    path('inflows/create/', views.InflowCreateView.as_view(), name='inflow_create'),
    path('inflows/<int:pk>/detail/', views.InflowDetailView.as_view(), name='inflow_detail'),
    path('inflows/<int:pk>/update/', views.InflowUpdateView.as_view(), name='inflow_update'),
    path('inflows/<int:pk>/delete/', views.InflowDeleteView.as_view(), name='inflow_delete')
]

brands/models.py
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name
    

inflows/models.py
from django.db import models
from suppliers.models import Supplier
from products.models import Product


class Inflow(models.Model):
    supplier = models.ForeignKey(Supplier,on_delete=models.PROTECT, related_name='inflows')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='inflows')
    quantity = models.IntegerField()
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return str(self.product)

inflows/forms.py
from django import forms
from . import models


class InflowForm(forms.ModelForm):

    class Meta:
        model = models.Inflow
        fields = ['supplier', 'product', 'quantity', 'description']
        widgets = {
            'supplier': forms.Select(attrs={'class': 'form-control'}),
            'product': forms.Select(attrs={'class': 'form-control'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }
        labels = {
            'supplier': 'Fornecedor',
            'product': 'Produto',
            'quantity': 'Quantidade',
            'description': 'Descrição',
        }

inflows/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from . import models, forms


class InflowListView(ListView):
    model = models.Inflow
    template_name = 'inflow_list.html'
    context_object_name = 'inflows'
    paginate_by = 10

    def get_queryset(self): #Sobreescrevendo e Filtrando uma Brand pelo nome
        queryset = super().get_queryset()
        name = self.request.GET.get('name')
        print("VALOR NAME", name)

        if name:
            queryset = queryset.filter(name__icontains=name)
        print("Queryset:", queryset)
        return queryset

class InflowCreateView(CreateView):
    model = models.Inflow
    template_name = 'inflow_create.html'
    form_class = forms.InflowForm
    success_url = reverse_lazy('inflow_list')

class InflowDetailView(DetailView):
    model = models.Inflow
    template_name = 'inflow_detail.html'

class InflowUpdateView(UpdateView):
    model = models.Inflow
    template_name = 'inflow_update.html'
    form_class = forms.InflowForm
    success_url = reverse_lazy('inflow_list')

class InflowDeleteView(DeleteView):
    model = models.Inflow
    template_name = 'inflow_delete.html'
    success_url = reverse_lazy('inflow_list')

inflows/templates/inflow_create.html
{% extends "base.html" %}

{% block title %}{% endblock title %}

{% block content %}

<div class="container mt-4">
    <h3 class="diplay-4">Cadastrar Marca</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Marca</button>

            </form>
        </div>
    </div>
    <a href="{% url 'brand_list' %}" class="btn btn-secondary mt-3">Cancelar</a>
</div>

{% endblock content %}

inflows/templates/inflow_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h3 class="display-6">Deletar Marca</h3>
    <div class="card">
        <div class="card-body">
            <p class="card-text">Tem certeza que deseja excluir a marca <strong>{{object.name}}</strong> ?</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger mt-3">Deletar</button>

            </form>
            
        </div>
        
    </div>
    <a href="{% url 'brand_list' %}" class="btn btn-secondary mt-3">Cancelar</a>
</div>

{% endblock content %}

inflows/templates/inflow_detail.html
{% extends "base.html" %}

{% block title %}Detalhes{% endblock title %}

{% block content %}

    <div class="container mt-4">
        <h3 class="display-6">Detalhes da Marca</h3>

        <div class="card">
            <div class="card-body">
                <h3 class="card-title">{{ object.name }}</h3>
                <p class="card-text">{{ object.description }}</p>
            </div>
        </div>
        <a href="{% url 'brand_list' %}" class="btn btn-secondary mt-3">Voltar</a>
    </div>

{% endblock content %}

inflows/templates/inflow_list.html
{% extends "base.html" %}

{% block title %} SGE - FORNECEDORES{% endblock title %}

{% block content %}

<div class="row mb-3">
    <div class="col-md-6">
        <form method="get" action="{% url 'brand_list' %}">
            <div class="input-group">
                <input type="text" class="form-control" name="name" placeholder="Nome" value="{{ request.GET.name }}">
                <button type="submit" class="btn btn-primary"><i class="bi bi-search"></i></button>
            </div>
        </form>
    </div>
    {% comment %} <div class="col-md-6">
        <a href="{% url 'brand_create' %}" class="btn btn-success float-end"><i class="bi bi-plus"></i>Nova Marca</a>
    </div> {% endcomment %}
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Produto</th>
                <th>Fornecedor</th>
                <th>Quantidade</th>
                <th>Data de Etrega</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for inflow in inflows %}
            <tr>
                <th><a href="{% url 'inflow_detail' inflow.id %}" class="text-primary fw-semibold"></a>{{ inflow.id }}</th>
                <td>{{ inflow.product }}</td>
                <td>{{ inflow.supplier }}</td>
                <td>{{ inflow.quantity }}</td>
                <td>{{ inflow.created_at }}</td>
                <td>
                    <a href="{% url 'inflow_detail' inflow.id %}" class="btn btn-info btn-sm"><i class="bi bi-eye"></i></a>

                </td>
            </tr>

            {% endfor %}
        </tbody>

    </table>

</div>
{% include "components/_pagination.html" %}
{% endblock content %}

inflows/templates/inflow_update.html
{% extends "base.html" %}

{% block title %}{% endblock title %}

{% block content %}

    <div class="conatiner my-4">
        <h3 class="display-4">Editar Marca</h3>
        <div class="card">
            <div class="card-body">
                <form method="post" class="form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Salvar Marca</button>
                </form>
            </div>
        </div>

        <a href="{% url 'brand_list' %}" class="btn btn-secondary mt-3">Voltar</a>
    </div>

{% endblock content %}